# Generated by Django 5.0 on 2025-07-13 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Property Name')),
                ('id_no', models.CharField(max_length=50, unique=True, verbose_name='ID NO.')),
                ('type', models.CharField(max_length=100, verbose_name='Type')),
                ('purpose', models.CharField(max_length=100, verbose_name='Purpose')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Price')),
                ('sqft', models.PositiveIntegerField(verbose_name='Square Feet')),
                ('featured_sqft', models.PositiveIntegerField(blank=True, null=True, verbose_name='Featured Sqft')),
                ('room', models.PositiveIntegerField(verbose_name='Total Rooms')),
                ('bedroom', models.PositiveIntegerField(verbose_name='Bedrooms')),
                ('bath', models.PositiveIntegerField(verbose_name='Bathrooms')),
                ('big_yard', models.PositiveIntegerField(blank=True, null=True, verbose_name='Big Yard')),
                ('parking', models.BooleanField(default=False, verbose_name='Parking Available')),
                ('elevator', models.BooleanField(default=False, verbose_name='Elevator Available')),
                ('wifi', models.BooleanField(default=False, verbose_name='WiFi Available')),
                ('built_in', models.PositiveIntegerField(blank=True, null=True, verbose_name='Built Year')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Address')),
                ('description_short', models.TextField(blank=True, null=True, verbose_name='Short Description')),
                ('description_long', models.TextField(blank=True, null=True, verbose_name='Long Description')),
                ('featured', models.BooleanField(default=False, verbose_name='Featured Property')),
                ('date_posted', models.DateField(auto_now_add=True, verbose_name='Date Posted')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
            ],
            options={
                'ordering': ['-date_posted'],
            },
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='property_images/')),
                ('alt_text', models.CharField(blank=True, max_length=255, null=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='dashboard.property')),
            ],
        ),
    ]
