# Generated by Django 5.0 on 2025-07-15 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Land',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('postcode', models.CharField(blank=True, max_length=10)),
                ('land_type', models.CharField(choices=[('residential', 'Residential'), ('commercial', 'Commercial'), ('agricultural', 'Agricultural'), ('industrial', 'Industrial'), ('others', 'Others')], default='residential', max_length=20)),
                ('ownership_type', models.CharField(choices=[('freehold', 'Freehold'), ('leasehold', 'Leasehold'), ('inherited', 'Inherited'), ('others', 'Others')], default='freehold', max_length=20)),
                ('area_size', models.DecimalField(decimal_places=2, help_text='Area in Katha/Decimal/Bigha/etc.', max_digits=10)),
                ('road_width', models.DecimalField(blank=True, decimal_places=2, help_text='In feet', max_digits=6, null=True)),
                ('electricity', models.BooleanField(default=False)),
                ('gas', models.BooleanField(default=False)),
                ('water', models.BooleanField(default=False)),
                ('drainage', models.BooleanField(default=False)),
                ('legal_clearance', models.BooleanField(default=True)),
                ('contact_name', models.CharField(max_length=100)),
                ('contact_phone', models.CharField(max_length=20)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('main_image', models.ImageField(upload_to='lands sell/main_images/')),
                ('is_published', models.BooleanField(default=True)),
                ('posted_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
