# Generated by Django 5.0 on 2025-07-15 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_land'),
    ]

    operations = [
        migrations.AlterField(
            model_name='land',
            name='is_published',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='land',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='lands sell/main_images/'),
        ),
    ]
