# Generated by Django 5.0 on 2025-07-19 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_landimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landimage',
            name='image',
            field=models.ImageField(upload_to='lands_sell/extra_images/'),
        ),
    ]
