# Generated by Django 5.0 on 2025-07-19 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_teammember'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='contact_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='years_of_experience',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
