# Generated by Django 5.1.6 on 2025-07-21 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_teammember_contact_number_teammember_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='is_complete',
            field=models.BooleanField(default=False, verbose_name='Is Complete'),
        ),
    ]
