# Generated by Django 5.0 on 2025-07-26 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_clienttestimonial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clienttestimonial',
            name='is_approved',
            field=models.BooleanField(default=True),
        ),
    ]
