# Generated by Django 5.2.4 on 2025-08-06 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('pending', 'Pending'), ('sold', 'Sold'), ('draft', 'Draft')], default='draft', max_length=20, verbose_name='Status'),
        ),
    ]
