# Generated by Django 5.2.4 on 2025-08-06 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_property_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Interior/designs/'),
        ),
        migrations.CreateModel(
            name='DesignImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Interior/designs/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('design_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='dashboard.designitem')),
            ],
        ),
    ]
