# Generated by Django 5.2.4 on 2025-08-07 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_alter_designitem_image_designimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('ongoing', 'On Going'), ('ready_flat', 'Ready Flat'), ('complete', 'Complete Project'), ('upcoming', 'Upcoming')], default='draft', max_length=20, verbose_name='Status'),
        ),
    ]
