# Generated by Django 5.2.4 on 2025-08-09 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_feature_property_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='map_embed_url',
            field=models.URLField(blank=True, null=True, verbose_name='Iframe Link Only'),
        ),
    ]
