# Generated by Django 5.2.4 on 2025-08-10 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0022_alter_contactmessage_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='unit',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Units'),
        ),
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='property',
            name='sqft',
            field=models.CharField(max_length=50, verbose_name='Square Feet'),
        ),
    ]
