# Generated by Django 5.2.4 on 2025-08-10 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0023_property_unit_alter_property_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_number', models.CharField(max_length=20, verbose_name='Contact Number')),
                ('customer_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Customer Name')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('land_location', models.CharField(blank=True, max_length=255, null=True, verbose_name='Land Location')),
                ('land_size', models.CharField(blank=True, max_length=50, null=True, verbose_name='Land Size')),
                ('booking_date', models.DateField(blank=True, null=True, verbose_name='Booking Date')),
                ('status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='pending', max_length=20, null=True)),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Additional Notes')),
            ],
        ),
    ]
